# environment.yml
name: llm-postprocessing
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - tzdata=2024.2
  - pip

  # Core numeric libraries
  - numpy=2.0.1
  - pandas=2.2.3
  - networkx=3.1
  - gmpy2=2.1.9

  # PyTorch + CUDA runtime
  - pytorch=2.5.0
  - torchvision=0.20.0
  - torchaudio=2.5.0
  - pytorch-cuda=12.1
  - cudatoolkit=12.1

  # Install the rest via pip
  - pip:
    - accelerate==1.0.1
    - aiohappyeyeballs==2.4.3
    - aiohttp==3.10.10
    - aiosignal==1.3.1
    - annotated-types==0.7.0
    - anyio==4.6.2.post1
    - attrs==24.2.0
    - bitsandbytes==0.44.1
    - brotli==1.0.9
    - certifi==2024.6.9
    - cffi==1.16.1
    - charset-normalizer==3.1.0
    - datasets==3.0.2
    - dill==0.3.8
    - distro==1.9.0
    - filelock==3.12.0
    - frozenlist==1.4.1
    - fsspec==2024.2.0
    - httpx==0.27.2
    - huggingface-hub==0.26.1
    - jiter==0.6.1
    - openai==1.52.0
    - packaging==24.1
    - peft==0.13.2
    - pillow==10.1.0
    - propcache==0.2.0
    - psutil==6.1.0
    - pyarrow==17.0.0
    - pydantic==2.9.2
    - pydantic-core==2.23.4
    - PySocks==1.7.1
    - python-dateutil==2.9.0.post0
    - pytz==2024.2
    - PyYAML==6.0
    - regex==2024.9.11
    - requests==2.31.0
    - safetensors==0.4.5
    - six==1.16.0
    - sympy==1.13.1
    - tokenizers==0.20.1
    - tqdm==4.66.5
    - transformers==4.45.2
    - triton==3.1.0
    - typing-extensions==4.8.0
    - urllib3==2.0.4
    - xxhash==3.5.0
    - yarl==1.16.0
    - zstandard==0.20.0
